solve issues marked by SonarCloud as high severity
Deltares/D-FAST_Morphological_Impact pull request #114
Opened 2024-07-01 12:57 UTC by hrajagers

2024-07-01 20:56 UTC, hrajagers commented
@MRVermeulenDeltares  or @ralph-peelen-deltares  Would you be able to review these changes. I've tried to address all "high severity" issues identified by SonarCloud. Unfortunately, it doesn't seem to state whether they have actually been merged into the trunk ...

2024-07-02 05:29 UTC, ralph-peelen-deltares commented on dfastmi/batch/Face.py
> +    iface = numpy.nonzero(condition)[0]
Do you only want to get the 'True' values?

2024-07-02 05:45 UTC, ralph-peelen-deltares commented on dfastmi/batch/Projection.py
> +def project_one_xy_point_beyond_segment(
Unit test this method

2024-07-02 05:45 UTC, ralph-peelen-deltares commented on dfastmi/batch/Projection.py
> +def project_one_xy_point_onto_segment(
is this unit tested

2024-07-02 05:45 UTC, ralph-peelen-deltares commented on dfastmi/batch/Projection.py
> +def project_one_xy_point_onto_line(
no unit test?

2024-07-02 05:53 UTC, ralph-peelen-deltares commented on dfastmi/batch/Projection.py
> +def project_one_xy_point_onto_line(
is a private method, please update accordingly

2024-07-02 05:53 UTC, ralph-peelen-deltares commented on dfastmi/batch/core.py
> +def write_report_discharges(
is a private method, please update accordingly

2024-07-02 05:55 UTC, ralph-peelen-deltares commented on dfastmi/io/DataTextFileOperations.py
>              if hasHeader:
hasHeader = ralph implementatie... please use snake_case has_header

2024-07-02 05:57 UTC, ralph-peelen-deltares commented on dfastmi/io/DataTextFileOperations.py
> +                header = 0
header = 0 if hasHeader else None

2024-07-02 05:59 UTC, ralph-peelen-deltares commented on dfastmi/cli.py
> +def run_interactive_mode_once(
is private?

2024-07-02 06:05 UTC, ralph-peelen-deltares commented on dfastmi/cli.py
> +def write_report_data(
private?

2024-07-02 06:13 UTC, ralph-peelen-deltares requested changes
Please process remarks

2024-07-02 07:05 UTC, hrajagers reviewed
@ralph-peelen-deltares All comments processed. Code updated.

2024-07-02 07:05 UTC, hrajagers commented on dfastmi/io/DataTextFileOperations.py
>              if hasHeader:
Code updated.

2024-07-02 07:05 UTC, hrajagers commented on dfastmi/io/DataTextFileOperations.py
> +                header = 0
syntax adopted

2024-07-02 07:18 UTC, ralph-peelen-deltares approved these changes

2024-07-02 07:33 UTC, merged